- kubernetes/README.adoc
- kubernetes/pom.xml
- kubernetes/src/main/java/org/infinispan/tutorial/simple/kubernetes/InfinispanKubernetes.java
- pom.xml
- query/src/main/java/org/infinispan/tutorial/simple/query/InfinispanQuery.java
https://issues.jboss.org/browse/ISPN-6847
> ISPN-6847 Kubernetes in library mode

- c#/README.md
- c#/Simple.cs
- c#/simple.csproj
- c#/simple.sln
Fixed some error, added readme and removed x86 configuration (only 64 bit now)
This fixes #14
> HRCPP-307 Fixed errors

- javascript/index.js
https://issues.jboss.org/browse/ISPN-7335
> ISPN-7335 Fix JS client config

- pom.xml
- spring-session/README.md
- spring-session/pom.xml
- spring-session/src/main/java/org/infinispan/tutorial/simple/spring/SpringApp.java
- spring/pom.xml
https://issues.jboss.org/browse/ISPN-7305
> Ispn 7305/spring session tutorial

- spring-boot/README.adoc
- spring-boot/README.md
- spring-session/README.adoc
- spring-session/README.md
https://issues.jboss.org/browse/ISPN-7305
> ISPN-7305 Additional readme files for Spring tutorials

- kubernetes/README.adoc
- kubernetes/pom.xml
- spring-boot/pom.xml
- spring-boot/src/main/java/org/infinispan/tutorial/simple/spring/SpringBootApp.java
https://issues.jboss.org/browse/ISPN-8684
Plus, Spring Boot Starters update.
> Upgrade spring boot starters

- multimap/pom.xml
- multimap/src/main/java/org/infinispan/tutorial/simple/multimap/InfinispanMultimap.java
- pom.xml
- testAll.sh
https://issues.jboss.org/browse/ISPN-8805
> ISPN-8805 Simple tutorial multimap

- lock/pom.xml
- lock/src/main/java/org/infinispan/tutorial/simple/lock/InfinispanClusteredLock.java
- pom.xml
- testAll.sh
https://issues.jboss.org/browse/ISPN-8804
> ISPN-8804 Simple tutorial clustered lock

- pom.xml
- remote-counter/pom.xml
- remote-counter/src/main/java/org/infinispan/tutorial/simple/remote/counter/InfinispanRemoteCounter.java
- remote-tx/pom.xml
- remote-tx/src/main/java/org/infinispan/tutorial/simple/remote/counter/InfinispanRemoteTx.java
- testAll.sh
* Hot Rod Transactions
* Hot Rod Clustered Counters
note1: it depends on https://github.com/infinispan/infinispan-simple-tutorials/pull/46
note2: the code was copied from embedded tutorials
> Added Hot Rod Tx and Counters tutorial

- README.md
- clusterexec/pom.xml
- counter/pom.xml
- distexec/pom.xml
- distributed/pom.xml
- hibernate-cache/wildfly-local/pom.xml
- lock/pom.xml
- replicated/pom.xml
https://issues.jboss.org/browse/ISPN-9571
> ISPN-9571 Clustered tutorials should bind to localhost by default

- near-cache/pom.xml
- near-cache/src/main/java/org/infinispan/tutorial/simple/nearcache/InfinispanNearCache.java
- pom.xml
- spark/pom.xml
https://issues.jboss.org/browse/ISPN-9598
> ISPN-9598 Near cache simple tutorial

- hibernate-cache/spring-local/pom.xml
https://issues.jboss.org/browse/ISPN-9596
> ISPN-9596 Hibernate Spring simple tutorial should use Hibernate 5.2 compatible provider

- pom.xml
- remote-multimap/pom.xml
- remote-multimap/src/main/java/org/infinispan/tutorial/simple/remote/multimap/InfinispanRemoteMultimap.java
- spark/pom.xml
https://issues.jboss.org/browse/ISPN-9617
> ISPN-9617 remote multimap

- hibernate-cache/local/pom.xml
- hibernate-cache/spring-local/pom.xml
- pom.xml
https://issues.jboss.org/browse/ISPN-9676
> ISPN-9676 Update Hibernate cache tutorial to Spring 2.1

- invalidation-mode/pom.xml
- invalidation-mode/src/main/java/org/infinispan/tutorial/simple/invalidation/InvalidationMode.java
- pom.xml
https://issues.jboss.org/browse/ISPN-10045
> ISPN-10045 Invalidation mode simple tutorial

- spring-boot/embedded/pom.xml
- spring-boot/pom.xml
- spring-boot/remote/pom.xml
- spring-boot/remote/src/main/resources/application.properties
- spring-boot/remote/src/main/resources/hotrod-client.properties
https://issues.jboss.org/browse/ISPN-10044
> ISPN-10044 Upgrade spring-boot tutorial

- operator/README.md
- operator/minikube/Makefile
- operator/minikube/README.md
- operator/minikube/build.sh
- operator/minikube/deploy.sh
- operator/minikube/run.sh
- operator/minikube/test.sh
- operator/openshift/Makefile
- operator/openshift/README.md
- operator/openshift/build.sh
- operator/openshift/deploy.sh
- operator/openshift/run.sh
- operator/openshift/test.sh
Added test that demonstrates the operator simple tutorial can run on top of minikube.
It also adds IMAGE parameter to be able to test alternative operator image.
> Test alternative operator with minikube

- kubernetes/src/main/java/org/infinispan/tutorial/simple/kubernetes/InfinispanKubernetes.java
> Add default cache name to fix startup

- operator/README.md
https://issues.jboss.org/browse/ISPN-10568
> ISPN-10568 Operator creates external service

- README.md
- pom.xml
- remote-admin-create-cache/README.adoc
- remote-admin-create-cache/README.html
- remote-admin-create-cache/pom.xml
- remote-admin-create-cache/src/main/java/org/infinispan/tutorial/simple/remote/admin/InfinispanRemoteAdminCache.java
https://issues.redhat.com/browse/ISPN-11276
> ISPN-11276 example how to create caches with the remote API

- xsite-replication/README.md
- xsite-replication/create-data.sh
- xsite-replication/docker-compose.yaml
- xsite-replication/infinispan-xsite.xml
- xsite-replication/ny-backup-xsiteCache.xml
- xsite-replication/xsiteCache.xml
https://issues.jboss.org/browse/ISPN-10987
> ISPN-10987 Xsite simple tutorial

- remote-continuous-query/src/main/java/org/infinispan/tutorial/simple/remote/query/InfinispanRemoteContinuousQuery.java
- remote-listen/src/main/java/org/infinispan/tutorial/simple/remote/listen/InfinispanRemoteListen.java
- remote-multimap/src/main/java/org/infinispan/tutorial/simple/remote/multimap/InfinispanRemoteMultimap.java
- remote-query/src/main/java/org/infinispan/tutorial/simple/remote/query/InfinispanRemoteQuery.java
- remote-tx/pom.xml
- remote-tx/src/main/java/org/infinispan/tutorial/simple/remote/transaction/InfinispanRemoteTx.java
- remote/src/main/java/org/infinispan/tutorial/simple/remote/InfinispanRemote.java
https://issues.redhat.com/browse/ISPN-11469
> ISPN-11469 Fix get default cache

- pom.xml
- server-tasks/pom.xml
- server-tasks/src/main/java/org/infinispan/tutorial/simple/server/tasks/InfinispanServerTasks.java
- server-tasks/src/main/resources/META-INF/services/org.infinispan.tasks.ServerTask
- server-tasks/src/main/resources/hello.js
https://issues.redhat.com/browse/ISPN-11431
> Upgrade task tutorial

- near-cache/src/main/java/org/infinispan/tutorial/simple/nearcache/InfinispanNearCache.java
https://issues.jboss.org/browse/ISPN-11469
> ISPN-11469 near caching fix

- distributed/src/main/java/org/infinispan/tutorial/simple/distributed/InfinispanDistributed.java
- invalidation-mode/src/main/java/org/infinispan/tutorial/simple/invalidation/InvalidationMode.java
- lock/src/main/java/org/infinispan/tutorial/simple/lock/InfinispanClusteredLock.java
- query/src/main/java/org/infinispan/tutorial/simple/query/InfinispanQuery.java
- replicated/src/main/java/org/infinispan/tutorial/simple/replicated/InfinispanReplicated.java
- streams/src/main/java/org/infinispan/tutorial/simple/streams/InfinispanStreams.java
- tx/src/main/java/org/infinispan/tutorial/simple/tx/InfinispanTx.java
https://issues.jboss.org/browse/ISPN-11469
> ISPN-11469 Embedded tutorials fixed

- spring-boot/embedded/src/main/java/org/infinispan/tutorial/simple/spring/embedded/SpringBootApp.java
- spring-boot/pom.xml
- spring-boot/remote/src/main/java/org/infinispan/tutorial/simple/spring/remote/RemoteClientApp.java
- spring-session/pom.xml
- spring-session/src/main/java/org/infinispan/tutorial/simple/spring/embedded/SpringApp.java
- spring/README.adoc
- spring/pom.xml
- spring/src/main/java/org/infinispan/tutorial/simple/spring/embedded/SpringAnnotationConfiguration.java
- spring/src/main/java/org/infinispan/tutorial/simple/spring/embedded/SpringCaching.java
https://issues.redhat.com/browse/ISPN-11502
> ISPN-11502 Fix Spring tutorials

- spring-boot/embedded/src/main/java/org/infinispan/tutorial/simple/spring/embedded/SpringBootApp.java
- spring-boot/pom.xml
- spring-boot/remote/src/main/java/org/infinispan/tutorial/simple/spring/remote/RemoteClientApp.java
- spring-session/pom.xml
- spring-session/src/main/java/org/infinispan/tutorial/simple/spring/embedded/SpringApp.java
- spring/README.adoc
- spring/pom.xml
- spring/src/main/java/org/infinispan/tutorial/simple/spring/embedded/SpringAnnotationConfiguration.java
- spring/src/main/java/org/infinispan/tutorial/simple/spring/embedded/SpringCaching.java
https://issues.redhat.com/browse/ISPN-11502
> [10.1.x] ISPN-11502 Spring tutorials fix

- near-cache/src/main/java/org/infinispan/tutorial/simple/nearcache/InfinispanNearCache.java
- pom.xml
- remote-admin-create-cache/src/main/java/org/infinispan/tutorial/simple/remote/admin/InfinispanRemoteAdminCache.java
- remote-continuous-query/src/main/java/org/infinispan/tutorial/simple/remote/query/InfinispanRemoteContinuousQuery.java
- remote-listen/src/main/java/org/infinispan/tutorial/simple/remote/listen/InfinispanRemoteListen.java
- remote-multimap/src/main/java/org/infinispan/tutorial/simple/remote/multimap/InfinispanRemoteMultimap.java
- remote-query/src/main/java/org/infinispan/tutorial/simple/remote/query/InfinispanRemoteQuery.java
- remote-secured/src/main/java/org/infinispan/tutorial/simple/remote/InfinispanRemoteSecured.java
- remote/src/main/java/org/infinispan/tutorial/simple/remote/InfinispanRemote.java
- scripting/src/main/java/org/infinispan/tutorial/simple/scripting/InfinispanScripting.java
- server-tasks/src/main/java/org/infinispan/tutorial/simple/server/tasks/InfinispanServerTasks.java
- spring-boot/remote/README.adoc
- spring-boot/remote/src/main/java/org/infinispan/tutorial/simple/spring/remote/RemoteClientApp.java
- xsite-replication/docker-compose.yaml
https://issues.redhat.com/browse/ISPN-11644
> ISPN-11644 Upgrade to 10.1.6.Final

- near-cache/src/main/java/org/infinispan/tutorial/simple/nearcache/InfinispanNearCache.java
- pom.xml
- remote-admin-create-cache/src/main/java/org/infinispan/tutorial/simple/remote/admin/InfinispanRemoteAdminCache.java
- remote-continuous-query/src/main/java/org/infinispan/tutorial/simple/remote/query/InfinispanRemoteContinuousQuery.java
- remote-listen/src/main/java/org/infinispan/tutorial/simple/remote/listen/InfinispanRemoteListen.java
- remote-multimap/src/main/java/org/infinispan/tutorial/simple/remote/multimap/InfinispanRemoteMultimap.java
- remote-query/src/main/java/org/infinispan/tutorial/simple/remote/query/InfinispanRemoteQuery.java
- remote-secured/src/main/java/org/infinispan/tutorial/simple/remote/InfinispanRemoteSecured.java
- remote/src/main/java/org/infinispan/tutorial/simple/remote/InfinispanRemote.java
- scripting/src/main/java/org/infinispan/tutorial/simple/scripting/InfinispanScripting.java
- server-tasks/src/main/java/org/infinispan/tutorial/simple/server/tasks/InfinispanServerTasks.java
- spring-boot/remote/README.adoc
- spring-boot/remote/src/main/java/org/infinispan/tutorial/simple/spring/remote/RemoteClientApp.java
- xsite-replication/docker-compose.yaml
https://issues.redhat.com/browse/ISPN-11644
> [10.1.x] ISPN-11644 backport

- pom.xml
- remote-secured/src/main/java/org/infinispan/tutorial/simple/remote/InfinispanRemoteSecured.java
- spring-boot/remote/README.adoc
- xsite-replication/docker-compose.yaml
https://issues.redhat.com/browse/ISPN-11804
> ISPN-11804 upgrade to 11.0.0.Dev05

- near-cache/src/main/java/org/infinispan/tutorial/simple/nearcache/InfinispanNearCache.java
- remote-admin-create-cache/src/main/java/org/infinispan/tutorial/simple/remote/admin/InfinispanRemoteAdminCache.java
- remote-continuous-query/src/main/java/org/infinispan/tutorial/simple/remote/query/InfinispanRemoteContinuousQuery.java
- remote-listen/src/main/java/org/infinispan/tutorial/simple/remote/listen/InfinispanRemoteListen.java
- remote-multimap/src/main/java/org/infinispan/tutorial/simple/remote/multimap/InfinispanRemoteMultimap.java
- remote-query/src/main/java/org/infinispan/tutorial/simple/remote/query/InfinispanRemoteQuery.java
- remote-secured/src/main/java/org/infinispan/tutorial/simple/remote/InfinispanRemoteSecured.java
- remote/src/main/java/org/infinispan/tutorial/simple/remote/InfinispanRemote.java
- scripting/src/main/java/org/infinispan/tutorial/simple/scripting/InfinispanScripting.java
- server-tasks/src/main/java/org/infinispan/tutorial/simple/server/tasks/InfinispanServerTasks.java
- spring-boot/remote/src/main/java/org/infinispan/tutorial/simple/spring/remote/RemoteClientApp.java
https://issues.redhat.com/browse/ISPN-11812
> ISPN-11812 Remove getTemplateName() calls

- pom.xml
- remote-per-cache/pom.xml
- remote-per-cache/src/main/java/org/infinispan/tutorial/simple/remote/percache/InfinispanRemotePerCache.java
https://issues.redhat.com/browse/ISPN-12039
> ISPN-12039 Remote Per-Cache Simple Tutorial

- pom.xml
- remote-secured/src/main/java/org/infinispan/tutorial/simple/remote/InfinispanRemoteSecured.java
- scripting/src/main/java/org/infinispan/tutorial/simple/scripting/InfinispanScripting.java
- server-tasks/src/main/java/org/infinispan/tutorial/simple/server/tasks/InfinispanServerTasks.java
- testAll.sh
- xsite-replication/docker-compose.yaml
Other changes:
* Use the same credentials in all the Hot Rod examples
> Upgrade Infinispan to 11.0.1.Final

- remote-admin-create-cache/src/main/java/org/infinispan/tutorial/simple/remote/admin/InfinispanRemoteAdminCache.java
- remote-per-cache/src/main/java/org/infinispan/tutorial/simple/remote/percache/InfinispanRemotePerCache.java
https://issues.redhat.com/browse/ISPN-12141
> ISPN-12141 use the template enum

- operator/README.md
Update for operator simple tutorial
> Updated operator simple tutorial

- pom.xml
- remote-junit5/pom.xml
- remote-junit5/src/main/java/org/infinispan/tutorial/simple/remote/junit5/CachingService.java
- remote-junit5/src/test/java/org/infinispan/tutorial/simple/remote/junit5/CachingServiceTest.java
https://issues.redhat.com/browse/ISPN-12166
> ISPN-12166 Infinispan Server Extension tutorial

- hibernate-cache/spring-local/pom.xml
- pom.xml
- remote-secured/src/main/java/org/infinispan/tutorial/simple/remote/InfinispanRemoteSecured.java
- spring-integration/spring-boot/README.adoc
- spring-integration/spring-boot/embedded/pom.xml
- spring-integration/spring-boot/remote/pom.xml
- spring-integration/spring-boot/session-embedded/pom.xml
- spring-integration/spring-boot/session-remote/pom.xml
- spring-integration/spring/spring-session/pom.xml
- xsite-replication/docker-compose.yaml
* Update spring-boot dependencies
* Update server image
> Update to Infinispan 12.0.1.Final

- README.md
- operator/README.md
- pom.xml
- remote-admin-create-cache/src/main/java/org/infinispan/tutorial/simple/remote/admin/InfinispanRemoteAdminCache.java
- remote-continuous-query/src/main/java/org/infinispan/tutorial/simple/remote/query/InfinispanRemoteContinuousQuery.java
- remote-counter/src/main/java/org/infinispan/tutorial/simple/remote/counter/InfinispanRemoteCounter.java
- remote-listen/src/main/java/org/infinispan/tutorial/simple/remote/listen/InfinispanRemoteListen.java
- remote-multimap/src/main/java/org/infinispan/tutorial/simple/remote/multimap/InfinispanRemoteMultimap.java
- remote-per-cache/src/main/java/org/infinispan/tutorial/simple/remote/percache/InfinispanRemotePerCache.java
- remote-query/src/main/java/org/infinispan/tutorial/simple/remote/query/InfinispanRemoteQuery.java
- remote-secured/src/main/java/org/infinispan/tutorial/simple/remote/InfinispanRemoteSecured.java
- remote-tx/src/main/java/org/infinispan/tutorial/simple/remote/transaction/InfinispanRemoteTx.java
- remote/src/main/java/org/infinispan/tutorial/simple/remote/InfinispanRemote.java
- scripting/src/main/java/org/infinispan/tutorial/simple/scripting/InfinispanScripting.java
- server-tasks/src/main/java/org/infinispan/tutorial/simple/server/tasks/InfinispanServerTasks.java
- spring-integration/spring-boot/README.adoc
- spring-integration/spring-boot/remote/pom.xml
- spring-integration/spring-boot/remote/src/main/resources/application.properties
- spring-integration/spring-boot/session-remote/src/main/resources/application.properties
https://issues.redhat.com/browse/ISPN-12921
> ISPN-12921 Upgrade 12.1.0.Final

- hibernate-cache/local/pom.xml
- pom.xml
* Bump infinispan versiont to 12.1.3.Final
* Align protostream (4.4.1.Final) and log4j (2.14.0) versions
> Update Infinispan 12.1.3.Final

- pom.xml
- xsite-replication/docker-compose.yaml
- xsite-replication/infinispan-xsite.xml
https://issues.redhat.com/browse/ISPN-13091
> ISPN-13091 Upgrade to 12.1.4.Final

- spring-integration/spring-boot/remote/src/main/java/org/infinispan/tutorial/simple/spring/remote/BasqueName.java
- spring-integration/spring-boot/remote/src/main/java/org/infinispan/tutorial/simple/spring/remote/BasquesNamesSchemaBuilder.java
- spring-integration/spring-boot/remote/src/main/java/org/infinispan/tutorial/simple/spring/remote/InfinispanConfiguration.java
- spring-integration/spring-boot/remote/src/main/java/org/infinispan/tutorial/simple/spring/remote/Reader.java
- spring-integration/spring-boot/remote/src/main/resources/application.properties
- spring-integration/spring-boot/session-remote/src/main/java/org/infinispan/tutorial/simple/spring/session/InfinispanConfiguration.java
- spring-integration/spring-boot/session-remote/src/main/java/org/infinispan/tutorial/simple/spring/session/WebController.java
https://issues.redhat.com/browse/ISPN-12512
Closes #121
> ISPN-12512 Protostream with spring boot remote

- remote-query/pom.xml
- remote-query/src/main/java/org/infinispan/tutorial/simple/remote/query/InfinispanRemoteQuery.java
- remote-query/src/main/java/org/infinispan/tutorial/simple/remote/query/Person.java
- remote-query/src/main/java/org/infinispan/tutorial/simple/remote/query/QuerySchemaBuilder.java
https://issues.redhat.com/browse/ISPN-13097
> ISPN-13097 Protobuf remote query

- spring-integration/spring-boot/remote/src/main/java/org/infinispan/tutorial/simple/spring/remote/BasqueName.java
- spring-integration/spring-boot/remote/src/main/java/org/infinispan/tutorial/simple/spring/remote/BasqueNamesRepository.java
- spring-integration/spring-boot/remote/src/main/java/org/infinispan/tutorial/simple/spring/remote/BasquesNamesSchemaBuilder.java
- spring-integration/spring-boot/remote/src/main/java/org/infinispan/tutorial/simple/spring/remote/Reader.java
* Package name with - have query parse errors
* For the console, it's less confusing to use Key in String
https://issues.redhat.com/browse/ISPN-12512
> ISPN-12512 Fix some issues

- javascript/README.md
- javascript/index.js
- javascript/package.json
https://issues.redhat.com/browse/ISPN-13136
> ISPN-13136 Upgrade Node.js tutorial to js client  0.9.0

- hibernate-cache/spring-local/pom.xml
- pom.xml
- query/src/main/java/org/infinispan/tutorial/simple/query/InfinispanQuery.java
- query/src/main/java/org/infinispan/tutorial/simple/query/Person.java
- spring-integration/spring-boot/embedded/src/main/resources/infinispan.xml
Removed deprecated code from `query` tutotiral
> Upgrade to 12.1.6.Final

- remote-per-cache/src/main/java/org/infinispan/tutorial/simple/remote/percache/InfinispanRemotePerCache.java
- remote-per-cache/src/main/resources/config/cacheConfig.xml
> Improve per cache tutorial

- infinispan-embedded/cache-distributed/src/main/java/org/infinispan/tutorial/simple/distributed/InfinispanDistributed.java
https://github.com/infinispan/infinispan-simple-tutorials/issues/139
> entrySet() should use CACHE_MODE_LOCAL for local keys #139

- documentation/asciidoc/topics/ref_hotrod_java_tutorials.adoc
- infinispan-remote/connect-to-infinispan-server/src/main/java/org/infinispan/tutorial/simple/connect/Infinispan.java
- infinispan-remote/encoding/pom.xml
- infinispan-remote/encoding/src/main/java/org/infinispan/tutorial/simple/encoding/InfinispanEncodingCaches.java
- infinispan-remote/encoding/src/main/resources/jsonCache.xml
- infinispan-remote/encoding/src/main/resources/textCache.xml
- infinispan-remote/encoding/src/main/resources/xmlCache.xml
- infinispan-remote/per-cache-configuration/src/main/resources/config/cacheConfig.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-13032
> ISPN-13032 Simple tutorial with encoding change example

- integrations/hibernate/wildfly-local/pom.xml
https://issues.redhat.com/browse/ISPN-13564
> ISPN-13564 Compile with Java 17

- infinispan-remote/persistence/README.md
- pom.xml
> Upgrade to latest 13.0.6.Final

- infinispan-remote/cross-site-replication/docker-compose/docker-compose.yaml
https://issues.redhat.com/browse/ISPN-13764
> ISPN-13764 Docker compose entry point fixed

- infinispan-remote/cross-site-replication/docker-compose/docker-compose.yaml
- infinispan-remote/cross-site-replication/docker-compose/infinispan-xsite.xml
- infinispan-remote/persistence/README.md
- infinispan-remote/security/tls-authorization/server/infinispan-sCert.xml
- infinispan-remote/security/tls-authorization/server/infinispan-sCertAuth.xml
- infinispan-remote/security/tls-authorization/server/infinispan-uCert.xml
- infinispan-remote/security/tls-authorization/server/infinispan-uCertAuth.xml
- integrations/hibernate/local/pom.xml
- integrations/hibernate/spring-local/pom.xml
- integrations/spring-boot/cache-embedded/src/main/resources/infinispan.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-13770
> ISPN-13770 move to Infinispan 14

- documentation/asciidoc/topics/attributes/community-attributes.adoc
- documentation/asciidoc/topics/ref_hotrod_java_tutorials.adoc
- infinispan-remote/connect-to-infinispan-server/src/main/java/org/infinispan/tutorial/simple/connect/Infinispan.java
- infinispan-remote/redis-client/pom.xml
- infinispan-remote/redis-client/src/main/java/org/infinispan/tutorial/simple/redis/RedisClientCache.java
- pom.xml
https://issues.redhat.com/browse/ISPN-14214
> ISPN-14214 Redis connector simple tutorial

- documentation/asciidoc/topics/attributes/community-attributes.adoc
- documentation/asciidoc/topics/ref_hotrod_java_tutorials.adoc
- infinispan-remote/cache-admin-api/src/main/java/org/infinispan/tutorial/simple/remote/admin/InfinispanRemoteAdminCache.java
- infinispan-remote/cache/src/main/java/org/infinispan/tutorial/simple/remote/InfinispanRemoteCache.java
- infinispan-remote/connect-to-infinispan-server/src/main/java/org/infinispan/tutorial/simple/connect/TutorialsConnectorHelper.java
- infinispan-remote/continuous-query/src/main/java/org/infinispan/tutorial/simple/remote/query/InfinispanRemoteContinuousQuery.java
- infinispan-remote/counter/src/main/java/org/infinispan/tutorial/simple/remote/counter/InfinispanRemoteCounter.java
- infinispan-remote/encoding/src/main/java/org/infinispan/tutorial/simple/encoding/InfinispanEncodingCaches.java
- infinispan-remote/listeners/src/main/java/org/infinispan/tutorial/simple/remote/listen/InfinispanRemoteListen.java
- infinispan-remote/multimap/src/main/java/org/infinispan/tutorial/simple/remote/multimap/InfinispanRemoteMultimap.java
- infinispan-remote/near-cache/src/main/java/org/infinispan/tutorial/simple/nearcache/InfinispanNearCache.java
- infinispan-remote/per-cache-configuration/src/main/java/org/infinispan/tutorial/simple/remote/percache/InfinispanRemotePerCache.java
- infinispan-remote/persistence/sql-store/src/main/java/org/infinispan/tutorial/simple/remote/persistence/SQLStoreLibraryMain.java
- infinispan-remote/query/src/main/java/org/infinispan/tutorial/simple/remote/query/InfinispanRemoteQuery.java
- infinispan-remote/reactive-api/pom.xml
- infinispan-remote/reactive-api/src/main/java/org/infinispan/tutorial/simple/reactive/InfinispanReactiveApi.java
- infinispan-remote/redis-client/src/main/java/org/infinispan/tutorial/simple/redis/RedisClientCache.java
- infinispan-remote/security/secured-cache/src/main/java/org/infinispan/tutorial/simple/remote/InfinispanAuthorizationCache.java
- infinispan-remote/security/tls-authorization/src/main/java/org/infinispan/tutorial/simple/security/tls/InfinispanTlsConnection.java
- infinispan-remote/tasks/src/main/java/org/infinispan/tutorial/simple/server/tasks/InfinispanServerTasks.java
- infinispan-remote/transactions/src/main/java/org/infinispan/tutorial/simple/remote/transaction/InfinispanRemoteTx.java
- pom.xml
Check the tutorial code overral please @wburns and @jabolina 
Any further suggestion is more than welcome
> ISPN-14269 Reactive API tutorial

- Jenkinsfile
- integrations/hibernate/spring-local/pom.xml
- pom.xml
https://issues.redhat.com/browse/ISPN-14576
> ISPN-14576 Update Infinispan to 14.0.7.Final

- integrations/hibernate/local/pom.xml
- integrations/hibernate/local/src/main/java/org/infinispan/tutorial/simple/hibernate/cache/local/InfinispanHibernateCacheLocal.java
- integrations/hibernate/local/src/main/java/org/infinispan/tutorial/simple/hibernate/cache/local/model/Event.java
- integrations/hibernate/local/src/main/java/org/infinispan/tutorial/simple/hibernate/cache/local/model/Person.java
- integrations/hibernate/spring-local/pom.xml
- integrations/hibernate/spring-local/src/main/java/org/infinispan/tutorial/simple/hibernate/cache/spring/local/InfinispanHibernateCacheSpringLocal.java
- integrations/hibernate/spring-local/src/main/java/org/infinispan/tutorial/simple/hibernate/cache/spring/local/model/Event.java
- integrations/hibernate/spring-local/src/main/java/org/infinispan/tutorial/simple/hibernate/cache/spring/local/model/Person.java
- pom.xml
* Update Infinispan version to 14.0.8
* Update Hibernate version in Hibernate Local to 6.2.0
* Update Spring version in Hibernate tutorial to 3.0.5 and use infinispan-hibernate-cache-v62
> Update Hibernate Local and Spring tutorials to Hibernate62

- integrations/hibernate/local/pom.xml
- integrations/hibernate/spring-local/pom.xml
- integrations/spring-boot/cache-embedded/pom.xml
- integrations/spring-boot/cache-remote/pom.xml
- integrations/spring-boot/session-embedded/pom.xml
- integrations/spring-boot/session-remote/pom.xml
- pom.xml
* Remove duplicated properties
* Ensure all modules use the same Infinispan version
> Upgrade Infinispan to 14.0.9.Final

- documentation/asciidoc/topics/ref_secured_with_token_keycloak.adoc
- infinispan-remote/infinispan-secured-keycloak/docker-compose-no-linux.yaml
- infinispan-remote/infinispan-secured-keycloak/infinispan-token-realm-no-linux.yaml
> no linux keycloak tutorial

- integrations/spring-boot/cache-remote/src/main/resources/application.properties
this is not the recommended way anymore
> drop near caching configuration

- infinispan-remote/connect-to-infinispan-server/src/main/java/org/infinispan/tutorial/simple/connect/TutorialsConnectorHelper.java
- infinispan-remote/cross-site-replication/pom.xml
- infinispan-remote/cross-site-replication/src/main/java/org/infinispan/tutorial/simple/remote/xsite/InfinispanRemoteSwitchCluster.java
- pom.xml
Java example with switch cluster
> add a cluster switch example in java

- infinispan-remote/query/src/main/java/org/infinispan/tutorial/simple/remote/query/InfinispanRemoteQuery.java
- infinispan-remote/query/src/main/java/org/infinispan/tutorial/simple/remote/query/Person.java
- infinispan-remote/query/src/main/java/org/infinispan/tutorial/simple/remote/query/PersonKey.java
- infinispan-remote/query/src/main/java/org/infinispan/tutorial/simple/remote/query/TutorialSchema.java
https://issues.redhat.com/browse/ISPN-16204
https://issues.redhat.com/browse/ISPN-13401
> ISPN-16204 Query by key, projection and delete by query tutorial

- infinispan-remote/reactive-api/pom.xml
- infinispan-remote/reactive-api/src/main/java/org/infinispan/tutorial/simple/reactive/InfinispanReactiveApi.java
- infinispan-remote/reactive-api/src/test/java/org/infinispan/tutorial/simple/reactive/InfinispanReactiveApiTest.java
15.1 removed the dependency and moved to the infinispan hotrod client the reactive api
> Fixes reactive api with the recent changes

- infinispan-remote/infinispan-secured-keycloak/docker-compose-no-linux.yaml
- infinispan-remote/infinispan-secured-keycloak/docker-compose.yaml
- infinispan-remote/infinispan-secured-keycloak/infinispan-keycloak-realm.json
> Fix Keycloak tutorial Closes #285

- .github/dependabot.yml
- .github/workflows/pull_requests.yml
- infinispan-remote/cross-site-replication/docker-compose/docker-compose.yaml
- infinispan-remote/infinispan-secured-keycloak/docker-compose-no-linux.yaml
- infinispan-remote/infinispan-secured-keycloak/docker-compose.yaml
- infinispan-remote/opentelemetry/docker-compose/docker-compose.yaml
- infinispan-remote/security/tls-authorization/server/infinispan-sCert.xml
- infinispan-remote/security/tls-authorization/server/infinispan-sCertAuth.xml
- infinispan-remote/security/tls-authorization/server/infinispan-uCert.xml
- infinispan-remote/security/tls-authorization/server/infinispan-uCertAuth.xml
- pom.xml
Closes https://github.com/infinispan/infinispan-simple-tutorials/issues/291
> Update to 15.1.0.Final

- pom.xml
> [15.0] Updates to 15.0.13.Final

- infinispan-remote/connect-to-infinispan-server/src/main/java/org/infinispan/tutorial/simple/connect/TutorialsConnectorHelper.java
- integrations/spring-boot/cache-remote-reactor/src/main/java/org/infinispan/tutorial/simple/spring/remote/InfinispanConfiguration.java
- integrations/spring-boot/cache-remote/src/main/java/org/infinispan/tutorial/simple/spring/remote/InfinispanConfiguration.java
- integrations/spring-boot/session-remote/src/main/java/org/infinispan/tutorial/simple/spring/session/InfinispanConfiguration.java
- pom.xml
> Updates to 15.1.15 and cleans BASIC intelligence

- infinispan-embedded/query/pom.xml
- infinispan-embedded/query/src/main/java/org/infinispan/tutorial/simple/query/Person.java
- pom.xml
> Use common annotations indexing
